# Generated by Django 3.0 on 2024-12-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0003_fullload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullload',
            name='loadId',
            field=models.IntegerField(max_length=250, null=True),
        ),
    ]
