# Generated by Django 3.0 on 2024-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0004_fullload_loadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullload',
            name='vehicleNo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
