# Generated by Django 3.0 on 2024-12-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0005_auto_20241209_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullload',
            old_name='Tone',
            new_name='tone',
        ),
    ]
