# Generated by Django 3.0 on 2024-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0006_auto_20241209_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullload',
            name='status',
            field=models.IntegerField(max_length=250, null=True),
        ),
    ]
