# Generated by Django 3.0 on 2024-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0007_fullload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullload',
            name='loadId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fullload',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
