# Generated by Django 3.0 on 2024-12-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0010_auto_20241210_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='full_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='consign_app.Fullload'),
        ),
        migrations.AlterField(
            model_name='fullload',
            name='paidAmt',
            field=models.FloatField(null=True),
        ),
    ]
