# Generated by Django 3.0 on 2024-12-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0011_auto_20241210_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='loadId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='change_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='full_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='consign_app.Fullload'),
        ),
    ]
