# Generated by Django 3.0 on 2024-12-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0013_auto_20241210_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullloadexpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Reason', models.CharField(max_length=150, null=True)),
                ('Amount', models.CharField(max_length=150, null=True)),
                ('branch', models.CharField(max_length=150, null=True)),
                ('staffname', models.CharField(max_length=150, null=True)),
                ('desc', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='balance',
            name='full_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='consign_app.Fullload'),
        ),
    ]
