# Generated by Django 3.0 on 2024-12-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0016_auto_20241213_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullload',
            name='driverName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='full_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='consign_app.Fullload'),
        ),
    ]
