# Generated by Django 3.0 on 2024-12-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0019_auto_20241218_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='dedicationAmt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='dedicationamtReason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='full_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='consign_app.Fullload'),
        ),
    ]
